set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"
set -s escape-time 0

# Fix extended-keys warning
set -g extended-keys on
set -g extended-keys-format csi-u

# Pass shift+enter through to the program (not intercepted by tmux's CSI-u parser)
bind -n S-Enter send-keys S-Enter

set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf
# windows start counting from 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows when one is closed
set -g renumber-windows on

# Set status bar to top
set -g status-position top

# allow mouse usage
set -g mouse on

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe 'pbcopy'

# vim-like pane switching
bind -r ^ last-window
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

set -g history-limit 50000